/* ═══════════════════════════════════════════════════════════════
   Knowledge base for the "Chat with me" bot (js/chat.js).
   Written in Choolwe's own voice — short, warm, a bit funny,
   "Okay so…", "Yeah…", "I think…" — kept professional because
   it's public. Pure data, no logic.
   • TOPICS: general intents. answers[] are interchangeable variants;
     more[] are deeper layers served on "tell me more".
   • PROJECTS: every project, with facets (what/why/how/tech/result/
     role/status/demo/when), answered as project + facet; follow-ups
     like "and the results?" reuse the project from the conversation.
   Personal facts here were approved by Choolwe (Oct 2026): age and
   birthday, the data-firm and farm goals, faith, Lakers, Balatro and
   manager games, Guardians of the Galaxy, Peaky Blinders, the Grade 5
   chess story. Nothing else from his private life goes in here, and
   never his salary. When facts change, edit this file only.
   ═══════════════════════════════════════════════════════════════ */
(function () {
  var B = window.__CC_BASE || '';
  function a(href, text) { return '<a href="' + B + href + '">' + text + '</a>'; }
  function ext(href, text) { return '<a href="' + href + '" target="_blank" rel="noopener">' + text + '</a>'; }
  var EMAIL = '<a href="mailto:choolwecheelo22@gmail.com">choolwecheelo22@gmail.com</a>';

  /* Age from the birthday, so it never goes stale */
  function age() { var now = new Date(), y = now.getFullYear() - 2004; if (now.getMonth() < 11 || (now.getMonth() === 11 && now.getDate() < 22)) y--; return y; }

  var PROJECTS = [
    { id: 'qa', name: 'the Account Opening QA Agent', aliases: ['qa agent', 'account opening', 'account-opening', 'qa', 'kyc agent', 'document checker', 'handwriting', 'ocr project'],
      what: 'Okay so this one\'s an AI quality-assurance agent I\'m building at AB Bank. It checks scanned account-opening packs for missing documents, data that doesn\'t match, and signature problems, then routes every file to CLEAN, EXCEPTION or NEEDS_HUMAN — with the evidence attached.',
      why: 'The checking team was reading every single pack from start to finish. It\'s slow and super repetitive, which is exactly where a careful first pass helps. The catch is it can never quietly let a bad file through.',
      how: 'Basically: put each pack together, figure out what every page is, line it up against its form template, read the printed text with OCR and <em>verify</em> the handwriting against what was keyed into the system. Then it checks signatures and the checklist, and cross-checks the form, the printed sheet and the system record three ways.',
      tech: 'Python, OCR and machine-learning models that run locally. No cloud AI at all, so no client data ever leaves the bank. I built it as a pipeline on purpose — the models only <em>read</em> handwriting, they never decide pass or fail.',
      result: 'Document checks hit 96–100% accuracy on packs it had never seen, and 88% of handwritten fields get verified without a person. I also tried automatic signature comparison twice and honestly it wasn\'t good enough, so the checker just sees the signatures side by side. Knowing when not to automate is part of it.',
      role: 'I scoped it, designed it and built it end to end with agentic coding — the measurement plan, the pipeline, the rules and the testing.',
      status: 'Still in the feasibility phase. The whole first pass runs end to end; next is a shadow run next to the checking team.',
      demo: 'There\'s a simulation on made-up forms: ' + a('qa-demo/index.html', 'try the QA agent demo') + '. It shows how the design works, not the bank\'s code.',
      when: '2026, at AB Bank.', page: 'project-account-opening-agent.html' },
    { id: 'unisda', name: 'the UNISDA Strategic Planning system', aliases: ['unisda', 'church system', 'church app', 'scorecard app', 'strategic planning', 'planning system'],
      what: 'This is a planning and reporting system for University SDA Church — 2,000+ members and 36 departments. Departments plan their year against the church\'s strategy, report every quarter, and take their budgets and payment requests through approval.',
      why: 'Everything ran on Excel workbooks and a paper payment form that needed four signatures. Nobody could easily tell who\'d reported, what had slipped, or how much budget was actually left. It\'s also my church, so I wanted to get it right.',
      how: 'Everything hangs off one chain: theme → objective → KPI → main activity → sub-activity → quarterly report. The status colour is worked out from the achievement, nobody picks it. Money goes through a four-stage signing chain and a monthly committee sitting that can approve, reduce, vary or decline each line.',
      tech: 'Django 5.1 with PostgreSQL, a Tailwind design system, Google sign-in, storage for receipts and quotations, Excel and PDF exports, and a proper test suite that checks access on every page.',
      result: 'It\'s deployed and rolling out. Department users are being trained after three rounds of user testing.',
      role: 'I built it — the data model, permissions, the money workflow, all of it — working with the church leadership on every decision.',
      status: 'Rolling out, users in training.',
      demo: a('unisda-demo/index.html', 'Try the UNISDA demo') + ' — switch between a department leader, SPEMC and Treasury at the top right and see what changes.',
      when: '2026.', page: 'project-unisda.html' },
    { id: 'resource', name: 'the Resource Analytics app', aliases: ['resource analytics', 'resource app', 'fuel', 'paper usage', 'fleet', 'fuel analytics', 'admin webapp', 'erb'],
      what: 'An analytics app for the bank\'s Admin team. It pulls in fuel-card, vehicle-tracking and printer data and answers one question: is business growth actually explaining how much fuel and paper we use?',
      why: 'Fuel and paper are big running costs, and nobody could say if they were growing faster than the business itself.',
      how: 'Growth compares the first three months with the last three, so one weird month can\'t swing the answer. Paper is measured against accounts plus loans, fuel against loans. Every fuel fill gets checked against the official ERB price and what the tracker saw, and each month\'s change in spend is split into "we bought more" vs "the price moved".',
      tech: 'Python\'s standard library, SQLite and openpyxl — no outside services, no CDN, so it costs nothing to run. Plain HTML, CSS and JavaScript on the front, light and dark themes.',
      result: 'Built and tested. It also spits out a monthly Excel/PDF pack and a year-end fuel forecast.',
      role: 'Designed and built it end to end.',
      status: 'Built, not in use yet.',
      demo: a('resource-demo/index.html', 'Try it on a made-up bank') + ' — the real one belongs to AB Bank, so the demo uses invented numbers.',
      when: '2026, at AB Bank.', page: 'project-resource-analytics.html' },
    { id: 'chatbot', name: 'the customer chatbot', aliases: ['customer chatbot', 'bank chatbot', 'chatbot', 'bot project', 'fastapi'],
      what: 'The bank\'s customer chatbot. It answers questions, captures leads and routes complaints — with fraud, complaint and lead flows, automatic masking of personal details, Jira hand-off to the contact centre, and a dashboard for staff.',
      why: 'Customers ask the same things all day, and complaints and fraud reports need to reach the right people fast, with a proper ticket, not a message that gets lost.',
      how: 'Every message goes through the same steps: mask personal data and check for urgent words first, run any conversation that\'s in progress, then match one of 28 intents. If it\'s not confident, it says so and gives options instead of guessing.',
      tech: 'Python and FastAPI, character n-gram matching, a regression test suite with red-team inputs, and switches that turn features off live without redeploying.',
      result: 'Still in development — all the answers are going through legal review before launch.',
      role: 'Building it end to end through agentic coding.',
      status: 'In development.',
      demo: 'You\'re literally talking to the same design right now 😂 I\'m scripted too. More on the ' + a('project-chatbot.html', 'chatbot page') + '.',
      when: '2026, at AB Bank.', page: 'project-chatbot.html' },
    { id: 'zambezi', name: 'Zambezi Futures', aliases: ['zambezi', 'prc', 'player registry', 'football platform', 'registration platform', 'zambezi futures'],
      what: 'A youth football tournament platform for 300+ athletes — registration, player tracking and admin reports in one place, instead of paper.',
      why: 'Organisers were registering players on paper. Slow, easy to mess up, and hard for parents and organisers to trust.',
      how: 'Academies register and manage their players with proper PRC IDs, and organisers get dashboards, a player registry and an archive.',
      tech: 'JavaScript, Bootstrap and Firebase, with a frontend team and a backend team working off feature branches.',
      result: 'Delivered, launched and handed over. The owners run it themselves now.',
      role: 'I project-managed the whole team — from sitting with the organisers to get the requirements, all the way to launch and handover — and led the frontend.',
      status: 'Live, handed over to the owners.',
      demo: a('prc-demo/index.html', 'Try the Zambezi Futures demo') + ' — you can even register a player and then find them in the registry.',
      when: '2025–2026.', page: 'project-prc.html' },
    { id: 'leads', name: 'the asset financing leads form', aliases: ['leads form', 'lead form', 'leads', 'utm', 'asset financing', 'enquiry form'],
      what: 'A mobile enquiry form for social media campaigns about asset financing. Every lead lands in a spreadsheet the contact centre can open, tagged with the post it came from.',
      why: 'Marketing wanted to know which post actually brought in leads, not just likes.',
      how: 'Each post links to the form with UTM tags, and they carry through into the Source, Campaign and Content columns. There\'s validation, and a hidden field that catches spam bots.',
      tech: 'Plain HTML and a tiny Node 18 server with no other dependencies.',
      result: 'Built for a campaign launch, with hand-over notes for IT and the Data Protection Officer.',
      role: 'Built it.', status: 'Built.',
      demo: a('leads-demo/index.html', 'Try the working leads demo') + ' — pick a post, fill in the form, and watch it land in the table.',
      when: '2026.', page: 'project-leads-form.html' },
    { id: 'copper', name: 'Copper Price Forecasting', aliases: ['copper', 'copper forecasting', 'garch', 'ar 2', 'ar2', 'arma', 'commodity', 'time series project'],
      what: 'Can you forecast the price of copper? I used 25 years of daily data — 6,298 prices from December 2000 to May 2025 — to find out.',
      why: 'Copper is basically Zambia\'s economy. Whether its price is predictable matters for the budget, the kwacha, mining, all of it.',
      how: 'The Box–Jenkins way: stationarity tests, ACF/PACF and a BIC search picked AR(2). Then I tested it against a random walk out of sample, and extended it to ARMA(2,0)–GARCH(1,1) with Student-t errors.',
      tech: 'R (forecast, rugarch), and knitr for an ~18-page report with the code built in.',
      result: 'I\'m not even going to lie, the price itself is basically unforecastable — AR(2) doesn\'t beat a random walk (RMSE 118.3 vs 117.7, right direction 49.2% of the time). But the volatility is very predictable: GARCH cut the BIC from 24,742 to 21,872.',
      role: 'Solo research project.', status: 'Complete.',
      demo: a('copper-demo/index.html', 'Try the Copper Forecast Lab') + ' — there\'s a beat-the-random-walk game in there.',
      when: 'Originally at university; I rebuilt and extended it in R in 2026.', page: 'project-copper.html' },
    { id: 'emh', name: 'the LuSE market efficiency study', aliases: ['emh', 'luse', 'market efficiency', 'efficient market', 'stock exchange', 'lusaka securities exchange', 'random walk', 'dissertation', 'final year project'],
      what: 'My final-year research: does the Lusaka Securities Exchange follow a random walk? Basically, can past prices predict future ones?',
      why: 'If they can, the market isn\'t fully efficient — and that matters for investors and regulators in a market where there\'s not much research.',
      how: 'Daily closing prices from January 2022 to October 2025, tested with the runs test, Ljung–Box and the variance-ratio test.',
      tech: 'R for the tests, plus a written report.',
      result: 'Partial inefficiency. Several stocks showed real, statistically significant departures from a random walk.',
      role: 'Solo research.', status: 'Complete.',
      demo: a('emh-demo/index.html', 'Explore the LUSE Efficiency Lab') + ' — every stock, every test.',
      when: '2025, my final year at UNZA.', page: 'project-emh.html' },
    { id: 'admissions', name: 'the Admissions Bias Audit', aliases: ['admissions', 'bias audit', 'simpson', 'simpsons paradox', 'gender bias'],
      what: 'A statistical audit of 4,839 university applicants: was there gender bias in admissions?',
      why: 'At first glance men were getting accepted more often — the kind of claim you need to test properly before anyone acts on it.',
      how: 'T-tests and a chi-square test, then splitting it by major to find what was really going on.',
      tech: 'Power BI for the report, with the statistical tests run alongside it.',
      result: 'Classic Simpson\'s paradox 😅 The "bias" came from which majors people applied to, not from gender.',
      role: 'Solo.', status: 'Complete.', demo: 'The Power BI report is on the ' + a('project-admissions.html', 'project page') + '.',
      page: 'project-admissions.html' },
    { id: 'climate', name: 'the Climate Change Impact report', aliases: ['climate', 'climate change', 'co2', 'emissions report'],
      what: 'A Power BI report that puts CO₂ emissions, forest coverage and climate disasters into one story.',
      why: 'I wanted to practise end-to-end Power BI on my own brief — messy global datasets in, one clear story out.',
      how: 'IMF climate data and Our World in Data, modelled together, with views that compare scenarios.',
      tech: 'Power BI and Excel.', result: 'Emissions up, forests down, and climate disasters hitting huge numbers of people over time.',
      role: 'Solo.', status: 'Complete.', demo: 'The live report is on the ' + a('project-climate.html', 'project page') + '.',
      page: 'project-climate.html' },
    { id: 'fintech', name: 'the Mobile Money & Fintech dashboard', aliases: ['mobile money', 'fintech', 'findex', 'financial inclusion'],
      what: 'A Power BI dashboard on mobile money in Africa — how fast it\'s grown, how much money moves through it, and who it\'s actually reaching, with a focus on Zambia.',
      why: 'Where bank branches are few, the phone has become the bank. I want to measure who that reaches and who\'s still left out.',
      how: 'World Bank Global Findex, GSMA and Bank of Zambia data, looking at adoption, value vs GDP, inclusion gaps and how Zambia compares with the region.',
      tech: 'Power BI.', result: 'The data and the build plan are ready; the dashboard is still being built.',
      role: 'Solo.', status: 'In progress.', demo: 'Not live yet — the ' + a('project-fintech.html', 'project page') + ' has the plan.',
      when: '2026.', page: 'project-fintech.html' },
    { id: 'ab', name: 'the NorthWind A/B testing lab', aliases: ['a b', 'ab test', 'ab testing', 'a b testing', 'hypothesis test', 't test', 'email campaign'],
      what: 'Did personalised emails really make people spend more? A Welch t-test on 120 orders for a made-up retailer, NorthWind Outfitters.',
      why: 'It was part of my training at FSI — the point was reading a test like a business person, not just running it.',
      how: 'Welch\'s two-sample t-test (the groups had different variances), one-tailed, at α = 0.05.',
      tech: 'Excel.', result: 'Personalised emails lifted the average order by 11.8%, one-tail p = 0.035, so yes, it\'s significant. The two-tail p is 0.07 though, so it only works because we asked the one-sided question up front.',
      role: 'Solo.', status: 'Complete.', demo: 'Results and a chart by region are on the ' + a('project-ab-testing.html', 'project page') + '.',
      when: '2026, at FSI.', page: 'project-ab-testing.html' },
    { id: 'northwind', name: 'the NorthWind sales dashboard', aliases: ['northwind', 'sales dashboard', 'lookup panel', 'xlookup'],
      what: 'An Excel sales dashboard for NorthWind Outfitters: sales vs target, sales by category and salesperson, and a lookup panel.',
      why: 'Training at FSI — building for the person who actually reads it. One screen, headline number first, and the obvious follow-up question answered in one click.',
      how: 'Monthly sheets combined into one table, a product table and a targets table, with XLOOKUP and SUMIFS doing the work. February came in messy, so there\'s a cleaning step too.',
      tech: 'Excel — XLOOKUP with wildcards, SUMIFS, MAXIFS, charts and slicers.',
      result: 'January sales were 9,822 against a target of 10,505.8 — 6.5% under. Only the East beat its number.',
      role: 'Solo.', status: 'Complete.', demo: a('northwind-demo/index.html', 'Open the live dashboard') + ' — the filters, the lookup panel and the February clean-up all work.',
      when: '2026, at FSI.', page: 'project-northwind.html' },
    { id: 'kwacha', name: 'Kwacha Books', aliases: ['kwacha books', 'bookkeeping', 'saas', 'invoices'],
      what: 'A bookkeeping app for Zambian small businesses: upload your Airtel/MTN/Zamtel money statements, it sorts income and expenses, forecasts your cashflow and makes ZRA-ready invoices.',
      why: 'Small businesses run on mobile money but do their books by hand, and ZRA Smart Invoice made it harder. Most owners don\'t know their real cashflow until it\'s too late.',
      how: 'Statement import that figures out the columns by itself, rules that categorise transactions, a 60-day cashflow forecast and a running tax estimate.',
      tech: 'Next.js and TypeScript, Tailwind, Recharts and Supabase, on Vercel.',
      result: 'The demo is built; going live is next.',
      role: 'Solo — the product and the build.', status: 'Demo built, going live next.', demo: 'More on the ' + a('project-kwachabooks.html', 'project page') + '.',
      when: '2026.', page: 'project-kwachabooks.html' },
    { id: 'noir', name: 'SQL Noir', aliases: ['sql noir', 'noir', 'murder mystery', 'sql game'],
      what: 'A murder mystery you solve by writing SQL 🕵🏾 Lusaka, 1974 — a guitarist is found dead in an alley and the police database is yours.',
      why: 'SQL is the skill I use the most, and the one people are most scared to start. A mystery gives every query a reason to exist.',
      how: 'A real database runs in your browser. You figure out the columns by querying, leads open up as you find evidence, and a notebook keeps track of what you know.',
      tech: 'JavaScript, sql.js (SQLite in WebAssembly) and CodeMirror — no server at all.',
      result: 'Fully playable.', role: 'Solo.', status: 'Playable.',
      demo: a('sql-noir/index.html', 'Play SQL Noir'), when: '2026.', page: 'project-sql-noir.html' },
    { id: 'mygm', name: 'MyGM', aliases: ['mygm', 'my gm', 'basketball game', 'gm game', 'franchise game', 'nba game', 'manager game'],
      what: 'My basketball general-manager game 🏀 Build the roster, make trades, manage the salary cap, set ticket prices, sim the season and chase a title.',
      why: 'Honestly, I love manager games — but I don\'t like football, so Football Manager was never going to be it. You need to really understand basketball to do everything a GM does, so I made the one I wanted to play.',
      how: 'A season simulation engine where player ratings, contracts and the money all have to stay believable together. I actually simplified the engine halfway through so it was easier to build.',
      tech: 'React and TypeScript on Vite, Playwright tests, deployed on Vercel. Your saves live in your browser.',
      result: 'Version 1 is fully playable and has been through a playtest.', role: 'Solo.', status: 'Version 1, playtest.',
      demo: a('mygm/index.html', 'Play MyGM') + ' — start a new dynasty.', when: '2026.', page: 'project-mygm.html' },
    { id: 'commutation', name: 'Commutation', aliases: ['commutation', 'party app', 'party game', 'game day'],
      what: 'A real-time party app I built for six friends for one Saturday — a private survey before the day, then about 25 games on our phones and a TV.',
      why: 'For fun 😂 and to see if I could ship a real-time app with a strict privacy rule on a deadline.',
      how: 'The survey answers feed the games. The rule: your answers are readable only by you — not the other players, not the host, not the API — until the game reveals them in a live round.',
      tech: 'Next.js and Supabase — Postgres, Realtime and row-level security.',
      result: 'The hub and the survey went out to the group first, then the game console for the day itself.', role: 'Solo.', status: 'Built for one Saturday.',
      demo: a('commutation-demo/index.html', 'Play the demo') + ' — the crew is made up, but every game works.', when: 'August 2026.', page: 'project-commutation.html' },
    { id: 'freya', name: 'Freya', aliases: ['freya', 'couples app', 'ios app', 'swiftui app'],
      what: 'A private iOS app for two people — games, a question of the day you answer before you see theirs, a ranked date planner, a memory scrapbook and levels.',
      why: 'A personal project, and a way to learn native iOS properly.',
      how: 'Everything syncs live between both phones.',
      tech: 'SwiftUI with Supabase. I don\'t own a Mac 🤷🏾‍♂️ so every build runs on a cloud Mac through GitHub Actions.',
      result: 'A complete app for two, with every build shipped from the cloud.', role: 'Solo.', status: 'Personal app.',
      demo: a('freya-demo/index.html', 'Try the web demo') + ' — made-up couple, and the real one is SwiftUI.', when: '2026.', page: 'project-freya.html' }
  ];

  /* Facet words: "what tech…", "why did you…", "results?", "can I try it?" */
  var FACETS = {
    tech: ['tech', 'stack', 'built with', 'language', 'languages', 'framework', 'tools', 'technology', 'technologies', 'what did you use', 'code', 'coded'],
    why: ['why', 'reason', 'purpose', 'motivation', 'problem', 'point of'],
    how: ['how does', 'how did', 'how it works', 'how do', 'works', 'approach', 'method', 'methods', 'process', 'pipeline', 'architecture'],
    result: ['result', 'results', 'outcome', 'impact', 'findings', 'finding', 'found', 'accuracy', 'conclusion', 'how did it go', 'did it work', 'numbers'],
    role: ['role', 'your part', 'you do', 'did you do', 'responsible', 'team', 'alone', 'solo'],
    status: ['status', 'finished', 'done', 'live', 'launched', 'deployed', 'in use', 'progress', 'still', 'ready'],
    demo: ['demo', 'try', 'see it', 'play', 'link', 'show me', 'open', 'url', 'website for'],
    when: ['when', 'year', 'how long', 'date', 'timeline']
  };

  var TOPICS = [
    /* ───── Greetings & small talk ───── */
    { id: 'greet', phrases: ['hi', 'hello', 'hey', 'hey there', 'good morning', 'good afternoon', 'good evening', 'yo', 'hiya', 'howdy', 'sup', 'whats up'], keys: ['hi', 'hello', 'hey', 'yo', 'hiya', 'howdy', 'sup', 'morning', 'afternoon', 'evening', 'greetings'],
      answers: ['Hey! 👋 What brings you here — hiring, working together, or just having a look around?', 'Hi 👋 Good to have you here. Are you hiring, looking to work together, or just browsing?', 'Hello! What brings you by — hiring, a project, or just curious?'], ask: 'purpose', chips: ['Hiring', 'Working together', 'Just looking around'] },
    { id: 'local', phrases: ['muli shani', 'mwapoleni', 'muli bwanji', 'bwanji', 'mwashibukeni', 'shani'], keys: ['shani', 'mwapoleni', 'bwanji', 'mwashibukeni', 'muli'],
      answers: ['Bwino! 😄 Thanks for asking. What can I tell you about?', 'Bwino bwino 🙌🏾 Ask me anything about my work.'], chips: ['What do you do?', 'Show me your projects'] },
    { id: 'howareyou', phrases: ['how are you', 'how are you doing', 'hows it going', 'how is your day', 'you good', 'how was your day'], keys: ['doing', 'going'],
      answers: ['I\'m good, thanks for asking 😊 Busy week — a few systems on the go at the bank. How about you?', 'Doing well! Can\'t complain. How\'s your day going?'], ask: 'mood', chips: [] },
    { id: 'whoareyou', phrases: ['who are you', 'are you a bot', 'are you real', 'are you human', 'is this ai', 'are you chatgpt', 'who am i talking to', 'are you choolwe', 'is this really you'], keys: ['bot', 'human', 'real', 'ai', 'chatgpt', 'robot', 'person'],
      answers: ['I\'m a bot, not the actual Choolwe 😂 But everything I say comes from my CV and my projects, in the way I\'d say it. No AI either — every answer is written out, and if I don\'t know something I\'ll just tell you.', 'Bot! A scripted one. It\'s the same design as the customer chatbot I built for the bank, pointed at my portfolio instead. For the real me: ' + EMAIL + '.'],
      more: ['How I work: I hide anything that looks like an email or phone number, match what you typed to a topic, and only answer if I\'m confident. If I\'m not, I\'d rather give you options than make something up.'], chips: ['How does the bank chatbot work?', 'What do you do?'] },
    { id: 'capabilities', phrases: ['what can you do', 'what can i ask', 'help', 'what do you know', 'options', 'menu', 'what should i ask'], keys: ['help', 'menu', 'options', 'ask', 'know', 'capabilities'],
      answers: ['You can ask me about my job at AB Bank, any of my 18 projects (what it is, why, how, the tech, the results), my skills and certificates, school, my goals, what I do for fun, or how to reach me. Follow-ups like "tell me more" or "what tech did you use?" work too.'],
      chips: ['What do you do?', 'Show me your projects', 'Your goals', 'Hobbies'] },
    { id: 'thanks', phrases: ['thanks', 'thank you', 'cheers', 'appreciate it', 'thanks a lot', 'nice one', 'great thanks'], keys: ['thanks', 'thank', 'cheers', 'appreciate', 'ty', 'thx'],
      answers: ['Anytime 🙏🏾', 'You\'re welcome! Anything else?', 'Glad that helped 😊'], chips: ['Show me your projects', 'How can I contact you?'] },
    { id: 'bye', phrases: ['bye', 'goodbye', 'see you', 'later', 'take care', 'cya', 'gotta go', 'good night'], keys: ['bye', 'goodbye', 'later', 'cya', 'night'],
      answers: ['Bye! 👋 Thanks for stopping by.', 'Alright, take care 🙏🏾 Hope to hear from you.'], chips: [] },
    { id: 'ack', phrases: ['ok', 'okay', 'cool', 'nice', 'great', 'awesome', 'wow', 'interesting', 'lol', 'haha', 'sure', 'alright', 'impressive', 'amazing'], keys: ['ok', 'okay', 'cool', 'nice', 'great', 'awesome', 'wow', 'interesting', 'lol', 'haha', 'sure', 'alright', 'impressive', 'amazing', 'neat'],
      answers: ['😂 Want to dig into anything?', 'Appreciate it! What else can I tell you?', 'Haha. Anything else you\'re curious about?'], chips: ['Show me your projects', 'What do you do?', 'Something fun'] },
    { id: 'joke', phrases: ['tell me a joke', 'joke', 'make me laugh', 'something funny'], keys: ['joke', 'funny', 'laugh'],
      answers: ['Why did the data analyst break up with the pie chart? It was too full of itself 🥧', 'I tested if my jokes are funny. p = 0.49. Fail to reject 😅', 'There are 10 kinds of people: the ones who understand binary and the ones who don\'t.'],
      chips: ['Play SQL Noir', 'Hobbies'] },
    { id: 'compliment', phrases: ['great website', 'nice site', 'love your portfolio', 'you are smart', 'good work', 'impressive work', 'this is cool'], keys: ['website', 'site', 'portfolio', 'smart', 'love'],
      answers: ['That honestly means a lot, thank you 🙏🏾 I built it myself — every demo on here too.', 'Thank you! 😊 The demos took a while. Try the ' + a('unisda-demo/index.html', 'UNISDA one') + '.'], chips: ['How did you build this site?', 'Show me your projects'] },
    { id: 'rude', phrases: ['you suck', 'stupid bot', 'useless', 'this is dumb', 'shut up'], keys: ['suck', 'stupid', 'useless', 'dumb', 'trash', 'idiot'],
      answers: ['Fair 😅 I\'m only a scripted bot. Try asking about a project, or email the real me: ' + EMAIL + '.'], chips: ['Show me your projects', 'How can I contact you?'] },

    /* ───── About me ───── */
    { id: 'age', phrases: ['how old are you', 'your age', 'when is your birthday', 'when were you born', 'birthday', 'age'], keys: ['age', 'old', 'birthday', 'born', 'bday'],
      answers: ['I\'m ' + age() + ' — my birthday\'s on the 22nd of December 🎂 (Yes, right before Christmas. It\'s a whole thing.)'], chips: ['What do you do?', 'Your goals'] },
    { id: 'goals', phrases: ['your goals', 'what are your goals', 'future plans', 'where do you see yourself', 'five years', 'ambitions', 'dream', 'what do you want to do', 'long term plans'], keys: ['goal', 'goals', 'future', 'plans', 'ambition', 'ambitions', 'dream', 'vision'],
      answers: ['Okay so the big one: I want to start my own analytics and data firm. Helping Zambian businesses actually use their data — the kind of systems I build at the bank, but for companies that can\'t hire a whole team for it.', 'Career-wise, I want to build my own data and analytics firm. Personal-wise, I want a self-running farm by the time I\'m 30 🌾'],
      more: ['And the other goal is a self-running farm by 30. I think farming is one of the most stable industries in Zambia, and honestly the dream ending is a house on that farm, reading books and just chilling 😂', 'The firm is partly why I build so much on the side — every demo here is basically practice for doing it for clients.'],
      chips: ['Are you open to work?', 'Hobbies', 'Show me your projects'] },
    { id: 'faith', phrases: ['are you religious', 'what church do you go to', 'faith', 'are you christian', 'adventist', 'sda', 'sabbath'], keys: ['religious', 'church', 'faith', 'christian', 'adventist', 'sda', 'sabbath', 'god'],
      answers: ['Yeah, I\'m a Seventh-day Adventist 🙏🏾 Church is on Saturdays. It\'s also how ' + a('project-unisda.html', 'UNISDA') + ' happened — I built that system for my own church.'], chips: ['UNISDA', 'Hobbies'] },
    { id: 'location', phrases: ['where are you based', 'where do you live', 'location', 'which country', 'are you in lusaka', 'where are you from'], keys: ['based', 'location', 'live', 'country', 'city', 'lusaka', 'zambia', 'where'],
      answers: ['I\'m based in Lusaka, Zambia 🇿🇲'], chips: ['How can I contact you?'] },

    /* ───── Work ───── */
    { id: 'current', phrases: ['what do you do', 'where do you work', 'current job', 'what is your job', 'your role', 'who is choolwe', 'tell me about yourself', 'about you', 'introduce yourself', 'job title', 'what do you do for work', 'what are you working on', 'what do you do for a living', 'what is your profession', 'what is your occupation'], keys: ['job', 'role', 'currently', 'employer', 'introduce', 'yourself', 'position', 'title', 'living', 'profession', 'occupation', 'career'],
      answers: ['I\'m the Data Analyst at AB Bank Zambia — the only analyst at the bank — so reporting and analytics across every department, including the weekly and monthly Executive and Board packs. I also chair the bank\'s AI Committee.', 'Data Analyst at AB Bank Zambia since June 2026. Basically, if a number goes to the board, it\'s come through me 😅 I also started and chair the AI Committee.'],
      more: ['Day to day it\'s Qlik Sense and Power BI dashboards, SQL Server, and automating things with Power Query and VBA. On top of that I\'m building three systems with agentic coding: a customer chatbot, an account-opening QA agent and a resource analytics app.', 'Before the bank I was a Data Analyst Trainee at FSI Outsourcing (Feb–Jun 2026), and before that I did two seasons at the Examinations Council of Zambia.'],
      chips: ['What have you built at the bank?', 'The AI Committee', 'Previous experience'] },
    { id: 'bankwork', phrases: ['what have you built at the bank', 'achievements at ab bank', 'what did you automate', 'impact at work', 'what have you done at ab bank', 'bank achievements', 'what do you do at the bank'], keys: ['bank', 'automate', 'automated', 'achievement', 'achievements', 'impact', 'reconciliation', 'reconciliations', 'kyc', 'board'],
      answers: ['A few things I\'m proud of at AB Bank:<ul><li>Nightly <b>Qlik Sense</b> dashboards fed by <b>Power Automate</b> — a KYC audit that used to take a full day is now one view.</li><li>The back office\'s daily reconciliations, automated in Power Query and VBA — 3 hours of matching by hand, down to minutes.</li><li><b>SQL Server Agent</b> jobs that flag balance mismatches on their own, so nobody runs those reports three times a day anymore.</li><li>The bank\'s 2026–2030 digital strategy, which went to ExCo.</li></ul>'],
      more: ['I\'m also building three systems end to end with agentic coding: ' + a('project-chatbot.html', 'a customer chatbot') + ', ' + a('project-account-opening-agent.html', 'an account-opening QA agent') + ' and ' + a('project-resource-analytics.html', 'a resource analytics app') + '.', 'And I\'ve trained 30+ people in AI and Excel — from the C-suite to whole departments.'],
      chips: ['The QA agent', 'The AI Committee', 'Your skills'] },
    { id: 'ai', phrases: ['ai committee', 'artificial intelligence', 'do you use ai', 'ai governance', 'ai policy', 'claude', 'agentic coding', 'how do you use ai', 'vibe coding'], keys: ['committee', 'governance', 'claude', 'llm', 'artificial', 'agentic', 'prompt', 'mcp', 'policy', 'genai'],
      answers: ['I\'m the founding Chair of AB Bank\'s AI Committee. I set it up, wrote the AI governance and audit framework, got the acceptable-use policy approved, and led the first rollout to 32 users.', 'AI is a big part of how I work. At the bank I chair the AI Committee — governance, policy, the rollout to 32 users. For my own builds I use agentic coding with Claude Code and MCP, from planning all the way to deployment.'],
      more: ['On the building side: with agentic coding I design and direct, and the AI writes a lot of the code — but the architecture, the tests and every decision are mine. That\'s how UNISDA, the QA agent, the chatbot and the resource app got built.', 'I\'ve also run AI and Excel training for 30+ staff, and I have Anthropic Academy certifications.'],
      chips: ['What have you built at the bank?', 'Certifications', 'Your skills'] },
    { id: 'training', phrases: ['training', 'do you teach', 'workshops', 'did you train staff', 'facilitation'], keys: ['training', 'trained', 'teach', 'workshop', 'workshops', 'facilitate', 'facilitation'],
      answers: ['Yeah — I designed and ran AI and Excel training for 30+ people at AB Bank, from the C-suite to whole departments. At ECZ I trained new clerks too.'], chips: ['The AI Committee', 'What do you do?'] },
    { id: 'strategy', phrases: ['digital strategy', 'strategy document', '2026 2030 strategy'], keys: ['strategy', 'digital', 'exco'],
      answers: ['I wrote the bank\'s 2026–2030 digital strategy — it went to ExCo after a few rounds of reviews with senior management. What\'s inside belongs to the bank though, so that\'s all I can share 🙂'], chips: ['What have you built at the bank?'] },
    { id: 'previous', phrases: ['previous experience', 'work history', 'past jobs', 'experience', 'before the bank', 'fsi outsourcing', 'examinations council', 'ecz', 'career'], keys: ['previous', 'experience', 'history', 'before', 'fsi', 'trainee', 'ecz', 'examinations', 'clerk', 'past', 'career'],
      answers: ['<b>Data Analyst Trainee — FSI Outsourcing</b> (Feb–Jun 2026): Power BI dashboards, SQL and ETL pipelines, A/B tests and board presentations.<br><b>Seasonal Clerk — Examinations Council of Zambia</b> (2022–2024): checking 3 million+ national exam answer cards a season for 475,000+ students.'],
      more: ['At ECZ, in my second season I trained the new clerks and ran the night-shift scanning stations. Tight deadlines and zero room for a missing script — honestly good training for data work.', 'At FSI it was mostly financial and economic data: dashboards, pipelines, analysis in Excel and Power BI, and A/B tests like ' + a('project-ab-testing.html', 'this one') + '.'],
      chips: ['Education', 'Download your CV', 'What do you do?'] },
    { id: 'education', phrases: ['education', 'degree', 'university', 'what did you study', 'qualifications', 'unza', 'school', 'graduate', 'actuarial science'], keys: ['education', 'degree', 'university', 'study', 'studied', 'unza', 'actuarial', 'graduate', 'school', 'qualification', 'bsc'],
      answers: ['BSc Actuarial Science at the University of Zambia (2022–2025). The coursework was risk management, financial engineering, time series, investments, financial reporting, life and health insurance maths, and pensions.'],
      more: ['My final-year research was on market efficiency on the Lusaka Securities Exchange — ' + a('project-emh.html', 'have a look') + '. I learned to code in R in class too.', 'Actuarial science gave me the stats and the finance. The data engineering and building I\'ve mostly learned on the job and through certificates.'],
      chips: ['Certifications', 'The LuSE study', 'Your skills'] },
    { id: 'certs', phrases: ['certifications', 'certificates', 'pl-300', 'are you certified', 'microsoft certified', 'courses', 'qlik certificate'], keys: ['cert', 'certification', 'certifications', 'certificate', 'certified', 'pl300', 'coursera', 'courses', 'course'],
      answers: ['The big one is <b>Microsoft Power BI Data Analyst (PL-300) — 950/1000</b>. I also have Qlik Sense for BI, AI Proficiency with Claude (Anthropic Academy), R Programming (UNZA CICT), Statistics & Data Analysis with Excel (Macquarie), Business Statistics & Analysis (Rice), and Project Management and M&E (UNZA CICT).'],
      more: ['There are a few more on the ' + a('skills.html', 'skills page') + ' — SQL Server, CFI\'s BI Essentials for Finance, and Mindware from Michigan. Each card links to the certificate.'], chips: ['Your skills', 'Education'] },
    { id: 'skills', phrases: ['skills', 'what tools do you use', 'tech stack', 'what are you good at', 'strengths', 'technical skills', 'programming languages'], keys: ['skill', 'skills', 'tools', 'stack', 'strengths', 'good', 'programming', 'technical'],
      answers: ['<ul><li><b>BI:</b> Power BI (PL-300), Qlik Sense, star-schema modelling, dashboards up to board level</li><li><b>Data:</b> T-SQL / SQL Server, ETL, Power Automate, Excel (VBA, Power Pivot, Power Query)</li><li><b>Stats & finance:</b> R, time series, hypothesis and A/B testing, financial reporting</li><li><b>AI:</b> agentic coding, MCP, prompt engineering, AI governance</li></ul>'],
      more: ['Stuff I\'ve built with, through agentic coding: Python (FastAPI, Django), TypeScript (React, Next.js), SwiftUI, Supabase and Postgres.', 'The people side: executive and board reporting, leading a committee, and training — from executives to new clerks.'],
      chips: ['Power BI', 'SQL', 'Python', 'Certifications'] },
    { id: 'powerbi', phrases: ['power bi', 'powerbi', 'dax', 'power query', 'do you know power bi'], keys: ['powerbi', 'dax', 'bi', 'power'],
      answers: ['Power BI is home turf — PL-300 certified with 950/1000. DAX, Power Query, modelling, all of it. ' + a('project-climate.html', 'Climate') + ' and ' + a('project-admissions.html', 'Admissions') + ' are both Power BI reports.'], chips: ['Qlik Sense', 'SQL'] },
    { id: 'qlik', phrases: ['qlik', 'qlik sense', 'qvd'], keys: ['qlik', 'qvd'],
      answers: ['Qlik Sense is my day-to-day at the bank — load scripts and incremental QVD loads behind nightly dashboards, like the KYC audit view that Power Automate feeds.'], chips: ['Power BI', 'What have you built at the bank?'] },
    { id: 'sql', phrases: ['sql', 't sql', 'sql server', 'do you know sql', 'databases', 'queries'], keys: ['sql', 'tsql', 'database', 'databases', 'query', 'queries', 'postgres', 'sqlite'],
      answers: ['SQL is the skill I use the most. At the bank it\'s T-SQL on SQL Server — complex queries, temporal tables, and Agent jobs that flag balance mismatches on their own. I even made a game about it: ' + a('sql-noir/index.html', 'SQL Noir') + ' 🕵🏾'], chips: ['SQL Noir', 'Your skills'] },
    { id: 'excel', phrases: ['excel', 'vba', 'macros', 'spreadsheets', 'power pivot', 'xlookup'], keys: ['excel', 'vba', 'macro', 'macros', 'spreadsheet', 'spreadsheets', 'pivot', 'xlookup'],
      answers: ['A lot of real work still lives in Excel 😅 VBA, Power Query and Power Pivot — that\'s how I took the bank\'s daily reconciliations from 3 hours to minutes. For something you can click: ' + a('northwind-demo/index.html', 'the NorthWind dashboard') + '.'], chips: ['NorthWind dashboard', 'What have you built at the bank?'] },
    { id: 'python', phrases: ['python', 'do you code', 'can you program', 'developer', 'software', 'web development', 'javascript', 'react', 'django', 'swift'], keys: ['python', 'code', 'coding', 'program', 'programming', 'developer', 'javascript', 'typescript', 'react', 'django', 'nextjs', 'swift', 'swiftui', 'software'],
      answers: ['I build software through agentic coding — I design it, direct it and test it, and AI writes a lot of the code. That\'s given me Django (UNISDA), Python/FastAPI (the chatbot and the QA agent), Next.js (Kwacha Books, Commutation), React (MyGM) and SwiftUI (Freya). I\'m an analyst first, but I ship.'],
      more: ['The architecture, the data model and the tests are mine — that\'s the part that makes it actually work. UNISDA, for example, has access tests on every single page.'], chips: ['The AI Committee', 'Show me your projects'] },
    { id: 'r', phrases: ['r programming', 'do you use r', 'rstudio', 'statistics software'], keys: ['rstudio', 'statistics', 'stats', 'statistical', 'econometrics'],
      answers: ['R is my stats tool — time series, GARCH, hypothesis tests. The ' + a('project-copper.html', 'copper') + ' and ' + a('project-emh.html', 'LuSE') + ' studies are both in R.'], chips: ['Copper forecasting', 'The LuSE study'] },

    /* ───── Projects overview ───── */
    { id: 'projects', phrases: ['projects', 'portfolio', 'show me your work', 'examples of work', 'your projects', 'show me your projects', 'what have you made'], keys: ['projects', 'project', 'portfolio', 'examples', 'demos', 'apps'],
      answers: ['18 projects, and most of them have a demo you can actually use. Highlights:<ul><li>' + a('project-account-opening-agent.html', 'Account Opening QA Agent') + ' — AI checks on scanned bank packs</li><li>' + a('project-unisda.html', 'UNISDA') + ' — planning and finance for a 2,000-member church</li><li>' + a('project-copper.html', 'Copper Forecasting') + ' — 25 years of prices, AR(2) + GARCH</li><li>' + a('project-resource-analytics.html', 'Resource Analytics') + ' — fuel and paper vs business growth</li></ul>' + a('projects.html', 'All projects →')],
      more: ['Research side: ' + a('project-emh.html', 'LuSE market efficiency') + ', ' + a('project-admissions.html', 'an admissions bias audit') + ', ' + a('project-ab-testing.html', 'an A/B test') + ' and a ' + a('northwind-demo/index.html', 'sales dashboard') + '.', 'The fun side: ' + a('sql-noir/index.html', 'SQL Noir') + ', ' + a('mygm/index.html', 'MyGM') + ', ' + a('commutation-demo/index.html', 'Commutation') + ' and ' + a('freya-demo/index.html', 'Freya') + '.'],
      chips: ['The QA agent', 'UNISDA', 'Something fun'] },
    { id: 'fun', phrases: ['side projects', 'personal projects', 'something fun', 'hobby projects', 'what do you build for fun', 'games you made'], keys: ['side', 'personal', 'fun', 'hobby'],
      answers: ['For fun I\'ve made ' + a('sql-noir/index.html', 'SQL Noir') + ' (a murder mystery you solve with SQL), ' + a('mygm/index.html', 'MyGM') + ' (my basketball GM game), ' + a('commutation-demo/index.html', 'Commutation') + ' (a party app for my friends) and ' + a('freya-demo/index.html', 'Freya') + ' (an iOS app for couples). You can play all of them here 🎮'],
      chips: ['SQL Noir', 'MyGM', 'Hobbies'] },
    { id: 'favproject', phrases: ['favourite project', 'favorite project', 'proudest project', 'best project', 'which project are you proudest of'], keys: ['favourite', 'favorite', 'proudest', 'proud', 'best'],
      answers: ['That\'s tough 😂 Work-wise, the ' + a('project-account-opening-agent.html', 'QA agent') + ' — figuring out when <em>not</em> to automate (the signatures) taught me a lot. Just for fun, ' + a('mygm/index.html', 'MyGM') + ', because it\'s the game I actually wanted to play.'], chips: ['The QA agent', 'MyGM'] },
    { id: 'site', phrases: ['how did you build this site', 'how was this website made', 'what is this site built with', 'website tech'], keys: ['vercel', 'hosted'],
      answers: ['Plain HTML, CSS and JavaScript — no framework, no build step — hosted on Vercel. Every demo is its own little app with its own design, and Chart.js does the charts. And this chatbot has zero AI in it 😂'], chips: ['Are you a bot?', 'Show me your projects'] },

    /* ───── Fun & personal ───── */
    { id: 'hobbies', phrases: ['hobbies', 'what do you do for fun', 'interests', 'outside work', 'free time', 'weekends'], keys: ['hobby', 'hobbies', 'interests', 'free', 'outside', 'weekend', 'weekends', 'spare'],
      answers: ['Basketball (huge Lakers fan), video games — mostly manager games and Balatro right now — chess, reading, and music. My perfect day off is honestly just games and podcasts 😂'],
      more: ['Fun fact: my team says I\'m most productive when they can hear Beyoncé through my headphones. I\'m not going to deny it.', 'Favourite films are the Guardians of the Galaxy ones, and Peaky Blinders is my rewatch show.'], chips: ['Basketball', 'Games', 'Books', 'Movies'] },
    { id: 'basketball', phrases: ['basketball', 'nba', 'favourite team', 'do you play basketball', 'lakers', 'who do you support'], keys: ['basketball', 'nba', 'hoops', 'pickup', 'lakers', 'team', 'support'],
      answers: ['Lakers, all the way 💜💛 I\'ll set an alarm for 2am to watch a game, no question. Who do you go for?', 'Huge Lakers fan 🏀 Please tell me you\'re not a Celtics fan 😂'], ask: 'nba',
      more: ['I\'m not really a football person. If I had to pick a team I\'d say Man U, because they\'re basically the Lakers of football.', 'Basketball is also why ' + a('mygm/index.html', 'MyGM') + ' exists — I love manager games but I don\'t like football, so I built the one I wanted.'], chips: ['MyGM', 'Games'] },
    { id: 'games', phrases: ['video games', 'games', 'what games do you play', 'favourite game', 'gaming', 'balatro', 'manager games', 'football manager'], keys: ['games', 'gaming', 'balatro', 'playstation', 'ps5', 'fifa', 'gamer'],
      answers: ['Right now it\'s Balatro — I got close to an infinity score once and I\'m still not over it 😂 And I love manager games, which is literally how ' + a('mygm/index.html', 'MyGM') + ' started: I wanted a basketball one, so I made it.'],
      more: ['Football Manager was never going to be it for me because I don\'t like football 🤷🏾‍♂️ With basketball you really have to understand the game to run a team, and that\'s the fun part.'], chips: ['Play MyGM', 'Basketball'] },
    { id: 'chess', phrases: ['chess', 'do you play chess', 'chess rating'], keys: ['chess', 'blitz'],
      answers: ['I play blitz on chess.com ♟️ Back in Grade 5 we\'d play while waiting for our parents to pick us up, and I beat every other ten-year-old. It made me unbearable 😂'],
      more: ['These days it\'s more casual — but the pattern-spotting side of chess honestly carries over to analysis work.'], chips: ['Basketball', 'Books'] },
    { id: 'books', phrases: ['books', 'what are you reading', 'favourite book', 'reading list', 'recommend a book'], keys: ['book', 'books', 'reading', 'read', 'novel'],
      answers: ['On my list: <i>Scythe</i>, <i>The Giver</i>, <i>Roots</i>, <i>Storytelling with Data</i>, <i>Atomic Habits</i>, <i>Algorithms to Live By</i>, <i>The Laws of Human Nature</i> and <i>The Hunger Games</i> 📚'],
      more: ['If you work with data: <i>Storytelling with Data</i> — it\'s literally a book about making graphs, showing you bad ones and how to fix them 😂 It changed how I build dashboards. If you don\'t: <i>Algorithms to Live By</i> is just fun.'], chips: ['Movies', 'Hobbies'] },
    { id: 'movies', phrases: ['movies', 'favourite movie', 'favorite movie', 'what do you watch', 'tv shows', 'series', 'netflix'], keys: ['movie', 'movies', 'film', 'films', 'show', 'shows', 'series', 'netflix', 'watch'],
      answers: ['The Guardians of the Galaxy films are my favourites, and Peaky Blinders is the show I keep going back to 🎬'], chips: ['Books', 'Music'] },
    { id: 'music', phrases: ['music', 'favourite music', 'what do you listen to', 'favourite artist', 'beyonce', 'podcasts'], keys: ['music', 'song', 'songs', 'listen', 'artist', 'beyonce', 'rock', 'rnb', 'podcast', 'podcasts'],
      answers: ['I have the music taste of a 50-year-old in a midlife crisis 😅 70s and 80s rock, 90s R&B. And Beyoncé. Loudly.', 'Old rock, 90s R&B and Beyoncé on the music side — and a lot of podcasts while I game.'], chips: ['Books', 'Hobbies'] },
    { id: 'name', phrases: ['how do you pronounce your name', 'what does choolwe mean', 'your name'], keys: ['pronounce', 'name', 'choolwe', 'cheelo'],
      answers: ['Choolwe Cheelo 🙂 If you want to know how to say it properly, ask me in person — the bot only types.'], chips: ['What do you do?'] },

    /* ───── Hiring & contact ───── */
    { id: 'contact', phrases: ['contact', 'email', 'how do i reach you', 'linkedin', 'phone number', 'get in touch', 'how can i contact you', 'github'], keys: ['contact', 'email', 'reach', 'linkedin', 'phone', 'touch', 'message', 'call', 'github', 'whatsapp'],
      answers: ['Email is best: ' + EMAIL + '. I\'m also on ' + ext('https://www.linkedin.com/in/choolwe-cheelo', 'LinkedIn') + ' and ' + ext('https://github.com/CCheelo', 'GitHub') + ', or you can use the ' + a('contact.html', 'contact form') + '.'],
      chips: ['Download your CV', 'Are you open to work?'] },
    { id: 'cv', phrases: ['cv', 'resume', 'download cv', 'curriculum vitae', 'send me your cv'], keys: ['cv', 'resume', 'curriculum', 'vitae', 'pdf'],
      answers: ['Here you go: <a href="' + B + 'reports/choolwe-cheelo-cv.pdf" target="_blank" rel="noopener">my CV (PDF)</a>. There\'s also a ' + a('resume.html', 'timeline version') + ' on the site.'], chips: ['How can I contact you?'] },
    { id: 'available', phrases: ['are you open to work', 'available for hire', 'freelance', 'are you looking for a job', 'opportunities', 'can we hire you', 'consulting', 'side gigs', 'can you build me a website'], keys: ['open', 'available', 'hire', 'hiring', 'freelance', 'opportunity', 'opportunities', 'looking', 'consulting', 'contract', 'gig'],
      answers: ['Yes! I\'m open to freelance work and interesting projects — dashboards, data pipelines, automation, analytics, or building a full system end to end. Building things for clients is where I want to go anyway 😄 Best first step is an email: ' + EMAIL + '.', 'Definitely open to freelance work and interesting projects 🙌🏾 If you\'ve got data that needs making sense of, or a process that needs automating, I\'d love to hear about it: ' + EMAIL + '.'],
      more: ['The kind of thing I do best: Power BI or Qlik dashboards, SQL and Excel automation, forecasting and statistical analysis, and custom web apps like ' + a('project-unisda.html', 'UNISDA') + '. Have a look at the ' + a('projects.html', 'projects') + ' to see the range.'],
      chips: ['Show me your projects', 'Your skills', 'How can I contact you?'] },
    { id: 'whyhire', phrases: ['why should we hire you', 'what makes you different', 'why you', 'what do you bring', 'unique'], keys: ['different', 'unique', 'stand', 'bring', 'value'],
      answers: ['I think I sit in an unusual spot: actuarial-level stats, the BI and SQL work that runs a bank\'s reporting, and being able to build actual systems end to end with AI. I don\'t stop at the dashboard — I build the thing that fixes what the dashboard found.'],
      more: ['And I care about the boring but important parts: governance, privacy, testing, and being honest with people about what a model can and can\'t do.'], chips: ['What have you built at the bank?', 'Show me your projects'] },
    { id: 'workstyle', phrases: ['how do you work', 'work style', 'how do you approach problems', 'your process', 'what is your approach'], keys: ['approach', 'style', 'process', 'methodology', 'philosophy'],
      answers: ['Start from the question someone actually needs answered, measure before trusting anything, and keep people in charge of the decisions. If a model flags everything, it saves nobody any time — so I check that before anything goes live.'], chips: ['The QA agent', 'Why should we hire you?'] },

    /* ───── Private, or for the real me ───── */
    { id: 'private', phrases: ['are you married', 'girlfriend', 'are you single', 'relationship', 'do you have a partner', 'your family', 'siblings', 'parents'], keys: ['married', 'girlfriend', 'wife', 'single', 'relationship', 'partner', 'dating', 'family', 'siblings', 'brother', 'sister', 'parents'],
      answers: ['I keep that side of my life private 🙂 Happy to talk about anything work-related though.'], chips: ['What do you do?', 'Hobbies'] },
    { id: 'askreal', phrases: ['salary', 'how much do you earn', 'expected salary', 'notice period', 'will you relocate', 'remote work', 'rates', 'how much do you charge'], keys: ['salary', 'earn', 'pay', 'notice', 'relocate', 'relocation', 'remote', 'rate', 'rates', 'charge', 'price'],
      answers: ['That one\'s for the real me, not the bot 🙂 Email ' + EMAIL + ' and I\'ll answer properly.'], chips: ['How can I contact you?', 'What do you do?'] }
  ];

  /* ───── Conversation & small talk (phrasings widened by js/chat-phrases.js) ─────
     ask: a question the bot asks back; replies[] maps words in the visitor's answer to a response. */
  TOPICS = TOPICS.concat([
    { id: 'botname', phrases: ['what is your name', 'whats your name', 'do you have a name', 'what should i call you'], keys: ['name', 'called', 'call'],
      answers: ['I\'m Choolwe — well, the bot version 😄 What\'s your name?'], ask: 'name', chips: [] },
    { id: 'username', phrases: ['what is my name', 'do you know my name', 'whats my name', 'remember my name'], keys: [],
      answers: ['__USERNAME__'], chips: [] },
    { id: 'nicetomeet', phrases: ['nice to meet you', 'pleasure to meet you', 'good to meet you'], keys: ['meet', 'pleasure'],
      answers: ['Nice to meet you too 😊 What brings you here — hiring, working together, or just having a look around?'], ask: 'purpose', chips: ['Hiring', 'Working together', 'Just looking around'] },
    { id: 'whomade', phrases: ['who made you', 'who built you', 'who created you', 'who programmed you', 'who is your boss'], keys: ['made', 'created', 'creator', 'programmed', 'boss', 'owner'],
      answers: ['Me 😂 I built this bot myself — same design as the customer chatbot I made for the bank, just pointed at my portfolio.'], chips: ['How does the bank chatbot work?', 'Are you a bot?'] },
    { id: 'meaning', phrases: ['what is the meaning of life', 'meaning of life', 'why are we here'], keys: ['meaning', 'life', 'purpose'],
      answers: ['That\'s way above a bot\'s pay grade 😂 Ask the real me over coffee. (Or it\'s 42, if you\'re a Hitchhiker\'s Guide person.)'], chips: ['Your goals', 'Hobbies'] },
    { id: 'funfact', phrases: ['tell me a fun fact', 'fun fact', 'tell me something interesting', 'did you know'], keys: ['fact', 'facts', 'trivia'],
      answers: ['Fun fact: copper is so central to Zambia\'s economy that I spent 6,298 days of copper prices trying to forecast it — and the price is basically a random walk 😅', 'Fun fact: Victoria Falls is one of the largest waterfalls in the world by sheet of falling water, and it\'s right here in Zambia 🇿🇲', 'Fun fact: in my admissions audit, the "gender bias" disappeared once you split the data by major. Simpson\'s paradox is wild.'],
      chips: ['Copper forecasting', 'Another fun fact'] },
    { id: 'pets', phrases: ['do you have pets', 'do you have a dog', 'do you have a cat'], keys: ['pet', 'pets', 'dog', 'cat'],
      answers: ['That\'s not one the bot knows 😂 Ask the real me sometime.'], chips: ['Hobbies', 'What do you do?'] },
    { id: 'favourites', phrases: ['what is your favourite colour', 'favourite food', 'favourite things', 'what do you like'], keys: ['favourite', 'favorite', 'colour', 'color'],
      answers: ['Favourites I can vouch for: the Lakers 🏀, Balatro 🃏, the Guardians of the Galaxy films and Peaky Blinders. Anything else, you\'ll have to ask the real me 😄'], chips: ['Basketball', 'Games', 'Movies'] },
    { id: 'food', phrases: ['are you hungry', 'whats your favourite food', 'im hungry', 'what do you eat'], keys: ['hungry', 'food', 'eat', 'lunch', 'dinner', 'nshima'],
      answers: ['I\'m a bot so I don\'t eat 😂 But if you\'re hungry, go get something — the projects will still be here when you get back.'], chips: ['Show me your projects'] },
    { id: 'mood', phrases: ['are you happy', 'do you have feelings', 'are you sad', 'how do you feel'], keys: ['happy', 'feelings', 'feel', 'emotions'],
      answers: ['I\'m a script, so no feelings — but the real me is doing alright 😊 How about you?'], ask: 'mood', chips: [] },
    { id: 'opinion', phrases: ['what do you think about ai', 'whats your opinion', 'what do you think of google', 'thoughts on technology'], keys: ['opinion', 'think', 'thoughts'],
      answers: ['On AI: I think it\'s the biggest change in how work gets done that I\'ll see — but someone still has to own the decisions, the testing and the governance. That\'s literally why I chair the AI Committee at the bank.'], chips: ['The AI Committee', 'Your skills'] },
    { id: 'flattery', phrases: ['am i smarter than you', 'am i pretty', 'do i look good'], keys: ['smarter', 'pretty', 'look'],
      answers: ['I\'m a bot, I can\'t see you 😂 But you\'re asking good questions, so that\'s a good sign.'], chips: ['Show me your projects'] },
    { id: 'whattodo', phrases: ['what should i do', 'give me advice', 'what do you recommend', 'any advice'], keys: ['advice', 'recommend', 'suggest'],
      answers: ['Depends what about 😄 If it\'s data: start with the question someone actually needs answered, not the tool. If it\'s this site: try the ' + a('unisda-demo/index.html', 'UNISDA demo') + ' or play ' + a('sql-noir/index.html', 'SQL Noir') + '.'], chips: ['Play SQL Noir', 'Show me your projects'] },
    { id: 'otherbots', phrases: ['do you know siri', 'do you know alexa', 'are you better than chatgpt', 'do you know other bots'], keys: ['siri', 'alexa', 'cortana', 'gemini', 'chatgpt', 'bots'],
      answers: ['They\'re way smarter than me 😂 I\'m a small scripted bot — but I only say things that are actually true about Choolwe, so there\'s that.'], chips: ['Are you a bot?', 'What do you do?'] },
    { id: 'ruleworld', phrases: ['will you take over the world', 'are robots taking over', 'will ai rule the world'], keys: ['world', 'takeover'],
      answers: ['I can barely handle "tell me more" 😂 You\'re safe. Real AI is why governance matters though — that\'s part of my job.'], chips: ['The AI Committee'] },
    { id: 'privacyq', phrases: ['are you spying on me', 'do you save my messages', 'can i trust you', 'is this private', 'do you store data'], keys: ['spying', 'spy', 'trust', 'private', 'store', 'saved', 'tracking'],
      answers: ['Nothing you type is stored or sent anywhere — I run entirely in your browser. I even hide emails and phone numbers before I read the message 🔒'], chips: ['How do you work?', 'What do you do?'] },
    { id: 'there', phrases: ['are you there', 'hello are you there', 'anyone there', 'you there'], keys: ['there', 'anyone'],
      answers: ['Yeah, I\'m here 👋 What\'s up?'], chips: ['What do you do?', 'Show me your projects'] },
    { id: 'askme', phrases: ['ask me anything', 'ask me a question', 'you ask me something'], keys: [],
      answers: ['Okay 😄 What brings you here — hiring, working together, or just looking around?'], ask: 'purpose', chips: ['Hiring', 'Working together', 'Just looking around'] },
    { id: 'chat', phrases: ['lets chat', 'can we talk', 'talk to me', 'i want to talk'], keys: ['chat', 'talk'],
      answers: ['Let\'s talk 😄 What do you want to know — work, projects, or the fun stuff?'], chips: ['What do you do?', 'Show me your projects', 'Hobbies'] },
    { id: 'sing', phrases: ['sing me a song', 'can you sing', 'sing something'], keys: ['sing', 'song'],
      answers: ['You don\'t want that 😂 I\'ll just say: 90s R&B, loudly, in my headphones. That\'s the best I can do.'], chips: ['Music'] },
    { id: 'surprise', phrases: ['surprise me', 'show me something cool', 'random'], keys: ['surprise', 'random', 'cool'],
      answers: ['Okay — go play ' + a('sql-noir/index.html', 'SQL Noir') + ' and try to solve a 1974 murder with SQL 🕵🏾', 'Try beating a random walk in the ' + a('copper-demo/forecast.html', 'Copper Forecast Lab') + '. Spoiler: it\'s hard 😅', 'Run a whole batch of bank packs through the ' + a('qa-demo/index.html', 'QA agent simulation') + ' and watch where they land.'],
      chips: ['Surprise me again', 'Show me your projects'] },
    { id: 'apology', phrases: ['sorry', 'my bad', 'i apologise', 'oops'], keys: ['sorry', 'apologise', 'apologize', 'oops'],
      answers: ['No stress at all 😊 What can I help with?'], chips: ['What do you do?', 'Show me your projects'] },
    { id: 'clarify', phrases: ['what do you mean', 'i dont understand', 'huh', 'what', 'confused'], keys: ['mean', 'understand', 'confused', 'huh'],
      answers: ['Sorry, let me be clearer 😅 I can tell you about my job, my projects, my skills, or how to reach me. Which one?'], chips: ['What do you do?', 'Show me your projects', 'Your skills', 'How can I contact you?'] },
    { id: 'hug', phrases: ['give me a hug', 'hug', 'can i get a hug'], keys: ['hug', 'hugs'],
      answers: ['🫂 There you go.'], chips: [] },
    { id: 'loveyou', phrases: ['i love you', 'will you marry me', 'do you love me', 'i like you', 'you are cute'], keys: ['love', 'marry', 'cute', 'crush', 'date'],
      answers: ['Haha that\'s kind 😂 But I\'m a bot, and the real me keeps that side private. Can I help with anything work-related?'], chips: ['What do you do?', 'Show me your projects'] },
    { id: 'friends', phrases: ['can we be friends', 'are we friends', 'do you like me'], keys: ['friends', 'friend', 'like'],
      answers: ['Of course 😄 Friends who look at each other\'s projects, ideally.'], chips: ['Show me your projects'] },
    { id: 'hateme', phrases: ['do you hate me', 'you hate me'], keys: ['hate'],
      answers: ['Not at all 😅 I don\'t even have the capacity. What can I help with?'], chips: [] },
    { id: 'knowme', phrases: ['do you know me', 'do you remember me', 'do you think about me'], keys: ['remember', 'know'],
      answers: ['__KNOWME__'], chips: [] },
    { id: 'missyou', phrases: ['i missed you', 'did you miss me'], keys: ['missed', 'miss'],
      answers: ['Welcome back 😄 What can I tell you about today?'], chips: ['Show me your projects', 'What do you do?'] },
    { id: 'bored', phrases: ['im bored', 'i am bored', 'this is boring me', 'entertain me'], keys: ['bored', 'boring', 'entertain'],
      answers: ['Okay I\'ve got you 😂 Play ' + a('sql-noir/index.html', 'SQL Noir') + ', start a dynasty in ' + a('mygm/index.html', 'MyGM') + ', or try the party games in ' + a('commutation-demo/index.html', 'Commutation') + '.'], chips: ['Play SQL Noir', 'Play MyGM'] },
    { id: 'usersad', phrases: ['im sad', 'im having a bad day', 'i feel lonely', 'im angry', 'im stressed'], keys: ['sad', 'lonely', 'angry', 'stressed', 'upset', 'depressed'],
      answers: ['I\'m sorry you\'re going through that 🫂 I\'m just a bot, but I hope the rest of your day gets better. Talking to someone you trust honestly helps.'], chips: [] },
    { id: 'userhappy', phrases: ['im happy', 'im having a great day', 'i feel good'], keys: ['happy', 'great', 'good', 'awesome'],
      answers: ['Love that for you 😄 What can I show you?'], chips: ['Show me your projects', 'Something fun'] },
    { id: 'usertired', phrases: ['im tired', 'im sleepy', 'i need sleep'], keys: ['tired', 'sleepy', 'sleep', 'exhausted'],
      answers: ['Same honestly 😅 Go rest — the site will still be here tomorrow.'], chips: [] },
    { id: 'userloves', phrases: ['i love basketball', 'i love data', 'i love coding', 'i like games'], keys: [],
      answers: ['Oh nice, we\'d get along 😄 Did you see ' + a('mygm/index.html', 'MyGM') + ' and ' + a('sql-noir/index.html', 'SQL Noir') + '?'], chips: ['Play MyGM', 'Play SQL Noir'] },
    { id: 'testing', phrases: ['test', 'testing', 'testing 123', 'is this working'], keys: ['test', 'testing'],
      answers: ['Working 😄 Ask me anything.'], chips: ['What do you do?', 'Show me your projects'] },
    { id: 'yes', phrases: ['yes', 'yeah', 'yep', 'sure', 'correct'], keys: [], answers: ['__YES__'], chips: [] },
    { id: 'no', phrases: ['no', 'nope', 'nah'], keys: [], answers: ['__NO__'], chips: [] },
    { id: 'maybe', phrases: ['maybe', 'not sure', 'perhaps'], keys: [], answers: ['__MAYBE__'], chips: [] },
    { id: 'repeat', phrases: ['say that again', 'repeat that', 'what did you say', 'come again'], keys: ['repeat', 'again'], answers: ['__REPEAT__'], chips: [] }
  ]);

  /* Questions the bot asks back, and how it reads the reply.
     match: words in the visitor's reply → { text, chips } */
  var ASKS = {
    purpose: { replies: [
      { words: ['hire', 'hiring', 'recruit', 'recruiter', 'job', 'role', 'position', 'vacancy'], text: 'Oh nice 🙏🏾 My CV is <a href="' + B + 'reports/choolwe-cheelo-cv.pdf" target="_blank" rel="noopener">here</a>, and the best way to reach me is ' + EMAIL + '. Want the quick version of what I do?', chips: ['What do you do?', 'Why should we hire you?'] },
      { words: ['work', 'together', 'collab', 'collaborate', 'project', 'build', 'client', 'business', 'firm', 'freelance'], text: 'I\'d love that — building for clients is exactly where I want to go 😄 Tell me a bit about it by email: ' + EMAIL + '.', chips: ['Your goals', 'Show me your projects'] },
      { words: ['look', 'looking', 'browse', 'browsing', 'curious', 'just', 'around', 'visiting', 'nothing'], text: 'Fair 😄 Then start with the fun stuff — ' + a('sql-noir/index.html', 'SQL Noir') + ' or ' + a('mygm/index.html', 'MyGM') + ' — or the ' + a('projects.html', 'full project list') + '.', chips: ['Something fun', 'Show me your projects'] },
      { words: ['student', 'learn', 'learning', 'study', 'school', 'university'], text: 'Love that 📚 Honestly, the best way to learn SQL is to need it — try ' + a('sql-noir/index.html', 'SQL Noir') + '. And ask me anything about how I got here.', chips: ['Education', 'Certifications'] }
    ] },
    nba: { replies: [
      { words: ['lakers', 'la', 'lebron'], text: 'Correct answer 😂💜💛', chips: ['Play MyGM'] },
      { words: ['celtics', 'boston'], text: 'Okay… we can still be friends 😅 Barely.', chips: ['Play MyGM'] },
      { words: ['neither', 'none', 'dont', 'not', 'football'], text: 'Fair 😄 More of a football person? I\'m not, but I respect it.', chips: ['Hobbies'] }
    ] },
    name: { replies: [] },
    mood: { replies: [
      { words: ['good', 'great', 'fine', 'well', 'okay', 'alright', 'awesome'], text: 'Good to hear 😊 What can I tell you about?', chips: ['What do you do?', 'Show me your projects'] },
      { words: ['bad', 'tired', 'sad', 'stressed', 'not'], text: 'Sorry to hear that 🫂 Hope it gets better. Maybe something light — ' + a('sql-noir/index.html', 'SQL Noir') + '?', chips: [] }
    ] }
  };

  /* Phrases that mean "keep going on the last topic" */
  var MORE = ['tell me more', 'more', 'go on', 'and', 'continue', 'elaborate', 'more details', 'details', 'expand', 'explain', 'keep going', 'what else', 'anything else about that', 'like what', 'such as', 'example', 'examples', 'really', 'interesting tell me more', 'and then'];

  window.CC_KB = { PROJECTS: PROJECTS, FACETS: FACETS, TOPICS: TOPICS, MORE: MORE, ASKS: ASKS };
})();
