/* NorthWind Outfitters — data from Choolwe's course workbook (fictional company, made-up data).
   orders: the cleaned Jan + Feb orders (SalesAll); rawFeb: February as it arrived, before cleaning;
   products: the product dimension; targets: January sales targets by region. */
window.NW_DATA = {
 "orders": [
  {
   "id": "1001",
   "date": "2025-01-03",
   "region": "North",
   "rep": "Alex Smith",
   "customer": "Trail Hut",
   "pid": "PRD-001",
   "product": "TrekX Tent",
   "category": "Camping",
   "std": 120,
   "qty": 4,
   "price": 120,
   "total": 480
  },
  {
   "id": "1014",
   "date": "2025-01-18",
   "region": "North",
   "rep": "Alex Smith",
   "customer": "Ridge Gear",
   "pid": "PRD-001",
   "product": "TrekX Tent",
   "category": "Camping",
   "std": 120,
   "qty": 3,
   "price": 120,
   "total": 360
  },
  {
   "id": "1021",
   "date": "2025-01-27",
   "region": "West",
   "rep": "Maria Lopez",
   "customer": "Peak Outfitters",
   "pid": "PRD-001",
   "product": "TrekX Tent",
   "category": "Camping",
   "std": 120,
   "qty": 5,
   "price": 120,
   "total": 600
  },
  {
   "id": "2001",
   "date": "2025-02-01",
   "region": "North",
   "rep": "Alex Smith",
   "customer": "Trail Hutt",
   "pid": "PRD-001",
   "product": "Trekx Tent",
   "category": "Camping",
   "std": 120,
   "qty": 3,
   "price": 120,
   "total": 360
  },
  {
   "id": "2012",
   "date": "2025-02-18",
   "region": "West",
   "rep": "John King",
   "customer": "Mountain Edge",
   "pid": "PRD-001",
   "product": "Trekx Tent",
   "category": "Camping",
   "std": 120,
   "qty": 4,
   "price": 120,
   "total": 480
  },
  {
   "id": "1003",
   "date": "2025-01-05",
   "region": "South",
   "rep": "Alex Smith",
   "customer": "Outdoor World",
   "pid": "PRD-002",
   "product": "ForestLight Lantern",
   "category": "Camping",
   "std": 35,
   "qty": 10,
   "price": 35,
   "total": 350
  },
  {
   "id": "1005",
   "date": "2025-01-07",
   "region": "North",
   "rep": "Alex Smith",
   "customer": "Ridge Gear",
   "pid": "PRD-002",
   "product": "ForestLight Lantern",
   "category": "Camping",
   "std": 35,
   "qty": 2,
   "price": 36,
   "total": 72
  },
  {
   "id": "1023",
   "date": "2025-01-29",
   "region": "East",
   "rep": "Sarah Chen",
   "customer": "LakeSide Sports",
   "pid": "PRD-002",
   "product": "ForestLight Lantern",
   "category": "Camping",
   "std": 35,
   "qty": 4,
   "price": 35,
   "total": 140
  },
  {
   "id": "2007",
   "date": "2025-02-10",
   "region": "South",
   "rep": "John King",
   "customer": "Outdoor Wirld",
   "pid": "PRD-002",
   "product": "Forestlight Lantern",
   "category": "Camping",
   "std": 35,
   "qty": 8,
   "price": 35,
   "total": 280
  },
  {
   "id": "1004",
   "date": "2025-01-06",
   "region": "West",
   "rep": "John King",
   "customer": "Peak Outfitters",
   "pid": "PRD-003",
   "product": "SummitPro Jacket",
   "category": "Apparel",
   "std": 180,
   "qty": 3,
   "price": 180,
   "total": 540
  },
  {
   "id": "1008",
   "date": "2025-01-12",
   "region": "North",
   "rep": "Alex Smith",
   "customer": "Trail Hut",
   "pid": "PRD-003",
   "product": "SummitPro Jacket",
   "category": "Apparel",
   "std": 180,
   "qty": 1,
   "price": 185,
   "total": 185
  },
  {
   "id": "1015",
   "date": "2025-01-20",
   "region": "East",
   "rep": "Tom Rivera",
   "customer": "LakeSide Sports",
   "pid": "PRD-003",
   "product": "SummitPro Jacket",
   "category": "Apparel",
   "std": 180,
   "qty": 4,
   "price": 180,
   "total": 720
  },
  {
   "id": "2005",
   "date": "2025-02-06",
   "region": "North",
   "rep": "Tom Rivera",
   "customer": "Alpine Gear",
   "pid": "PRD-003",
   "product": "Summitpro Jacket",
   "category": "Apparel",
   "std": 180,
   "qty": 2,
   "price": 180,
   "total": 360
  },
  {
   "id": "2013",
   "date": "2025-02-22",
   "region": "East",
   "rep": "Sarah Chen",
   "customer": "Lakeside Sports",
   "pid": "PRD-003",
   "product": "Summitpro Jacket",
   "category": "Apparel",
   "std": 180,
   "qty": 3,
   "price": 180,
   "total": 540
  },
  {
   "id": "1002",
   "date": "2025-01-04",
   "region": "East",
   "rep": "Maria Lopez",
   "customer": "City Sports",
   "pid": "PRD-004",
   "product": "CloudRun Shoes",
   "category": "Footwear",
   "std": 80,
   "qty": 6,
   "price": 80,
   "total": 480
  },
  {
   "id": "1007",
   "date": "2025-01-10",
   "region": "South",
   "rep": "John King",
   "customer": "Adventure Hub",
   "pid": "PRD-004",
   "product": "CloudRun Shoes",
   "category": "Footwear",
   "std": 80,
   "qty": 8,
   "price": 78,
   "total": 624
  },
  {
   "id": "1024",
   "date": "2025-01-30",
   "region": "South",
   "rep": "Alex Smith",
   "customer": "Adventure Hub",
   "pid": "PRD-004",
   "product": "CloudRun Shoes",
   "category": "Footwear",
   "std": 80,
   "qty": 3,
   "price": 80,
   "total": 240
  },
  {
   "id": "2003",
   "date": "2025-02-04",
   "region": "South",
   "rep": "John King",
   "customer": "Adventure Hub",
   "pid": "PRD-004",
   "product": "CloudRun Shoes",
   "category": "Footwear",
   "std": 80,
   "qty": 5,
   "price": 80,
   "total": 400
  },
  {
   "id": "2005",
   "date": "2025-02-20",
   "region": "North",
   "rep": "Alex Smith",
   "customer": "Ridge Gears",
   "pid": "PRD-004",
   "product": "Cloudrun Shoes",
   "category": "Footwear",
   "std": 80,
   "qty": 7,
   "price": 80,
   "total": 560
  },
  {
   "id": "1006",
   "date": "2025-01-09",
   "region": "East",
   "rep": "Maria Lopez",
   "customer": "LakeSide Sports",
   "pid": "PRD-005",
   "product": "TrailBlaze Backpack",
   "category": "Camping",
   "std": 95,
   "qty": 5,
   "price": 95,
   "total": 475
  },
  {
   "id": "1016",
   "date": "2025-01-21",
   "region": "South",
   "rep": "Maria Lopez",
   "customer": "Adventure Hub",
   "pid": "PRD-005",
   "product": "TrailBlaze Backpack",
   "category": "Camping",
   "std": 95,
   "qty": 7,
   "price": 95,
   "total": 665
  },
  {
   "id": "1025",
   "date": "2025-01-31",
   "region": "North",
   "rep": "Tom Rivera",
   "customer": "Ridge Gear",
   "pid": "PRD-005",
   "product": "TrailBlaze Backpack",
   "category": "Camping",
   "std": 95,
   "qty": 6,
   "price": 95,
   "total": 570
  },
  {
   "id": "2002",
   "date": "2025-02-03",
   "region": "East",
   "rep": "Maria Lopez",
   "customer": "City Sports",
   "pid": "PRD-005",
   "product": "Trailblaze Backpack",
   "category": "Camping",
   "std": 95,
   "qty": 4,
   "price": 95,
   "total": 380
  },
  {
   "id": "2014",
   "date": "2025-02-25",
   "region": "South",
   "rep": "Tom Rivera",
   "customer": "Outdoor World",
   "pid": "PRD-005",
   "product": "Trailblaze Backpack",
   "category": "Camping",
   "std": 95,
   "qty": 6,
   "price": 95,
   "total": 570
  },
  {
   "id": "1009",
   "date": "2025-01-13",
   "region": "West",
   "rep": "Sarah Chen",
   "customer": "Mountain Edge",
   "pid": "PRD-006",
   "product": "Glacier Thermal Gloves",
   "category": "Apparel",
   "std": 25,
   "qty": 12,
   "price": 25,
   "total": 300
  },
  {
   "id": "1019",
   "date": "2025-01-24",
   "region": "East",
   "rep": "Alex Smith",
   "customer": "City Sports",
   "pid": "PRD-006",
   "product": "Glacier Thermal Gloves",
   "category": "Apparel",
   "std": 25,
   "qty": 10,
   "price": 25,
   "total": 250
  },
  {
   "id": "2009",
   "date": "2025-02-12",
   "region": "North",
   "rep": "Sarah Chen",
   "customer": "",
   "pid": "PRD-006",
   "product": "Glacier Thermal Gloves",
   "category": "Apparel",
   "std": 25,
   "qty": 10,
   "price": 25,
   "total": 250
  },
  {
   "id": "1010",
   "date": "2025-01-14",
   "region": "North",
   "rep": "Tom Rivera",
   "customer": "Alpine Gear",
   "pid": "PRD-007",
   "product": "StormGuard Raincoat",
   "category": "Apparel",
   "std": 140,
   "qty": 2,
   "price": 140,
   "total": 280
  },
  {
   "id": "1017",
   "date": "2025-01-22",
   "region": "West",
   "rep": "John King",
   "customer": "Mountain Edge",
   "pid": "PRD-007",
   "product": "StormGuard Raincoat",
   "category": "Apparel",
   "std": 140,
   "qty": 2,
   "price": 140,
   "total": 280
  },
  {
   "id": "2004",
   "date": "2025-02-05",
   "region": "West",
   "rep": "Sarah Chen",
   "customer": "Mountain Edge",
   "pid": "PRD-007",
   "product": "Stormguard Raincoat",
   "category": "Apparel",
   "std": 140,
   "qty": 3,
   "price": 140,
   "total": 420
  },
  {
   "id": "1011",
   "date": "2025-01-15",
   "region": "East",
   "rep": "Maria Lopez",
   "customer": "City Sports",
   "pid": "PRD-008",
   "product": "RiverFlow Kayak",
   "category": "Water Sports",
   "std": 430,
   "qty": 1,
   "price": 430,
   "total": 430
  },
  {
   "id": "1018",
   "date": "2025-01-23",
   "region": "North",
   "rep": "Sarah Chen",
   "customer": "Trail Hut",
   "pid": "PRD-008",
   "product": "RiverFlow Kayak",
   "category": "Water Sports",
   "std": 430,
   "qty": 1,
   "price": 430,
   "total": 430
  },
  {
   "id": "2006",
   "date": "2025-02-07",
   "region": "East",
   "rep": "Maria Lopez",
   "customer": "Lakeside Sports",
   "pid": "PRD-008",
   "product": "Riverflow Kayak",
   "category": "Water Sports",
   "std": 430,
   "qty": 1,
   "price": 430,
   "total": 430
  },
  {
   "id": "1012",
   "date": "2025-01-16",
   "region": "South",
   "rep": "John King",
   "customer": "Outdoor World",
   "pid": "PRD-009",
   "product": "PeakTrail Poles",
   "category": "Accessories",
   "std": 35,
   "qty": 15,
   "price": 35,
   "total": 525
  },
  {
   "id": "1022",
   "date": "2025-01-28",
   "region": "North",
   "rep": "John King",
   "customer": "Alpine Gear",
   "pid": "PRD-009",
   "product": "PeakTrail Poles",
   "category": "Accessories",
   "std": 35,
   "qty": 6,
   "price": 35,
   "total": 210
  },
  {
   "id": "2011",
   "date": "2025-02-17",
   "region": "South",
   "rep": "Maria Lopez",
   "customer": "Adventure Hub",
   "pid": "PRD-009",
   "product": "Peaktrail Poles",
   "category": "Accessories",
   "std": 35,
   "qty": 6,
   "price": 35,
   "total": 210
  },
  {
   "id": "1013",
   "date": "2025-01-17",
   "region": "West",
   "rep": "Sarah Chen",
   "customer": "Peak Outfitters",
   "pid": "PRD-010",
   "product": "SunShield Hat",
   "category": "Accessories",
   "std": 22,
   "qty": 20,
   "price": 22,
   "total": 440
  },
  {
   "id": "1020",
   "date": "2025-01-25",
   "region": "South",
   "rep": "Tom Rivera",
   "customer": "Outdoor World",
   "pid": "PRD-010",
   "product": "SunShield Hat",
   "category": "Accessories",
   "std": 22,
   "qty": 8,
   "price": 22,
   "total": 176
  },
  {
   "id": "2010",
   "date": "2025-02-14",
   "region": "East",
   "rep": "Tom Rivera",
   "customer": "City Sports",
   "pid": "PRD-010",
   "product": "Sunshield Hat",
   "category": "Accessories",
   "std": 22,
   "qty": 15,
   "price": 22,
   "total": 330
  },
  {
   "id": "2008",
   "date": "2025-02-11",
   "region": "West",
   "rep": "Alex Smith",
   "customer": "Peak Outfitters",
   "pid": "PRD-011",
   "product": "Arcticpro Sleeping Bag",
   "category": "Camping",
   "std": 150,
   "qty": 2,
   "price": 150,
   "total": 300
  }
 ],
 "rawFeb": [
  {
   "id": "2001",
   "date": "2025-02-01",
   "region": "North",
   "rep": "Alex Smith",
   "customer": "Trail Hutt",
   "pid": "Prd-001",
   "product": "Trekx Tent",
   "category": "Camping",
   "qty": 3,
   "price": 120,
   "total": 360
  },
  {
   "id": "2008",
   "date": "2025-02-11",
   "region": "West",
   "rep": "Alex Smith",
   "customer": "Peak Outfitters",
   "pid": "Prd-011",
   "product": "Arcticpro Sleeping Bag",
   "category": "Camping",
   "qty": 2,
   "price": 150,
   "total": 300
  },
  {
   "id": "2005",
   "date": "2025-02-20",
   "region": "North",
   "rep": "Alex Smith",
   "customer": "Ridge Gears",
   "pid": "Prd-004",
   "product": "Cloudrun Shoes",
   "category": "Footwear",
   "qty": 7,
   "price": 80,
   "total": 560
  },
  {
   "id": "2003",
   "date": "2025-02-04",
   "region": "South",
   "rep": "John King",
   "customer": "Adventure Hub",
   "pid": "Prd-004",
   "product": "",
   "category": "Footwear",
   "qty": 5,
   "price": 80,
   "total": 400
  },
  {
   "id": "2012",
   "date": "2025-02-18",
   "region": "West",
   "rep": "John King",
   "customer": "Mountain Edge",
   "pid": "Prd-001",
   "product": "Trekx Tent",
   "category": "Camping",
   "qty": 4,
   "price": 120,
   "total": 480
  },
  {
   "id": "2007",
   "date": "2025-02-10",
   "region": "South",
   "rep": "Jonh King",
   "customer": "Outdoor Wirld",
   "pid": "Prd-002",
   "product": "Forestlight Lantern",
   "category": "Camping",
   "qty": 8,
   "price": 35,
   "total": 280
  },
  {
   "id": "2002",
   "date": "2025-02-03",
   "region": "East",
   "rep": "Maria Lopez",
   "customer": "City Sports",
   "pid": "Prd-005",
   "product": "Trailblaze Backpack",
   "category": "Camping",
   "qty": 4,
   "price": 95,
   "total": 380
  },
  {
   "id": "2006",
   "date": "2025-02-07",
   "region": "East",
   "rep": "Maria Lopez",
   "customer": "Lakeside Sports",
   "pid": "Prd-008",
   "product": "Riverflow Kayak",
   "category": "Water Sports",
   "qty": 1,
   "price": 430,
   "total": 430
  },
  {
   "id": "2011",
   "date": "2025-02-17",
   "region": "South",
   "rep": "Maria Lopez",
   "customer": "Adventure Hub",
   "pid": "Prd-009",
   "product": "Peaktrail Poles",
   "category": "Accessories",
   "qty": 6,
   "price": 35,
   "total": 210
  },
  {
   "id": "2004",
   "date": "2025-05-02",
   "region": "West",
   "rep": "Sarah Chen",
   "customer": "Mountain Edge",
   "pid": "Prd-007",
   "product": "Stormguard Raincoat",
   "category": "Apparel",
   "qty": 3,
   "price": 140,
   "total": 420
  },
  {
   "id": "2009",
   "date": "2025-02-12",
   "region": "North",
   "rep": "Sarah Chen",
   "customer": "",
   "pid": "Prd-006",
   "product": "Glacier Thermal Gloves",
   "category": "",
   "qty": 10,
   "price": 25,
   "total": 250
  },
  {
   "id": "2013",
   "date": "2025-02-22",
   "region": "East",
   "rep": "Sarah Chen",
   "customer": "Lakeside Sports",
   "pid": "Prd-003",
   "product": "Summitpro Jacket",
   "category": "Apparel",
   "qty": 3,
   "price": 180,
   "total": 540
  },
  {
   "id": "2005",
   "date": "2025-02-06",
   "region": "North",
   "rep": "Tom Rivera",
   "customer": "Alpine Gear",
   "pid": "Prd-003",
   "product": "Summitpro Jacket",
   "category": "Apparel",
   "qty": 2,
   "price": 180,
   "total": 360
  },
  {
   "id": "2010",
   "date": "2004-02-14",
   "region": "East",
   "rep": "Tom Rivera",
   "customer": "City Sports",
   "pid": "Prd-010",
   "product": "Sunshield Hat",
   "category": "Accessories",
   "qty": 15,
   "price": 22,
   "total": 330
  },
  {
   "id": "2014",
   "date": "2025-02-25",
   "region": "South",
   "rep": "Tom Rivera",
   "customer": "Outdoor World",
   "pid": "Prd-005",
   "product": "Trailblaze Backpack",
   "category": "Camping",
   "qty": 6,
   "price": 95,
   "total": 570
  }
 ],
 "products": [
  {
   "pid": "PRD-001",
   "name": "TrekX Tent",
   "category": "Camping",
   "cost": 80,
   "price": 120
  },
  {
   "pid": "PRD-002",
   "name": "ForestLight Lantern",
   "category": "Camping",
   "cost": 20,
   "price": 35
  },
  {
   "pid": "PRD-003",
   "name": "SummitPro Jacket",
   "category": "Apparel",
   "cost": 110,
   "price": 180
  },
  {
   "pid": "PRD-004",
   "name": "CloudRun Shoes",
   "category": "Footwear",
   "cost": 55,
   "price": 80
  },
  {
   "pid": "PRD-005",
   "name": "TrailBlaze Backpack",
   "category": "Camping",
   "cost": 60,
   "price": 95
  },
  {
   "pid": "PRD-006",
   "name": "Glacier Thermal Gloves",
   "category": "Apparel",
   "cost": 12,
   "price": 25
  },
  {
   "pid": "PRD-007",
   "name": "StormGuard Raincoat",
   "category": "Apparel",
   "cost": 90,
   "price": 140
  },
  {
   "pid": "PRD-008",
   "name": "RiverFlow Kayak",
   "category": "Water Sports",
   "cost": 250,
   "price": 430
  },
  {
   "pid": "PRD-009",
   "name": "PeakTrail Poles",
   "category": "Accessories",
   "cost": 18,
   "price": 35
  },
  {
   "pid": "PRD-010",
   "name": "SunShield Hat",
   "category": "Accessories",
   "cost": 8,
   "price": 22
  }
 ],
 "targets": {
  "North": 3104.4,
  "East": 2295.4,
  "South": 2838.0,
  "West": 2268.0
 }
};
